import PaymentLicenseSuccess from "@/src/components/PaymentLicenseSuccess";

import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Payment Success | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <PaymentLicenseSuccess />
    </div>
  );
};

export default page;
