
import MemberValidate from "@/src/components/MemberValidate";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Login | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <MemberValidate/>
    </div>
  );
};

export default page;
