

import AdminProfile from "@/src/components/Profile/AdminProfile";

import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Admin Profile | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <AdminProfile />
    </div>
  );
};

export default page;
