import SingleNewsDashboard from "@/src/components/News/SingleNewsDashboard";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "News | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <SingleNewsDashboard />
    </div>
  );
};

export default page;
