import SingleNewsDashboard from "@/src/components/News/SingleNewsDashboard";
import { Metadata } from "next/types";
import React, { Suspense } from "react";
export const metadata: Metadata = {
  title: "News | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
       <Suspense fallback={<div>Loading navigation...</div>}>
      <SingleNewsDashboard />
      </Suspense>
    </div>
  );
};

export default page;
