
import ManagementUpgradeDashboard from "@/src/components/ManagementUpgrade/ManagementUpgradeDashboard";

import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Upgrade | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <ManagementUpgradeDashboard/>
    </div>
  );
};

export default page;
