import SingleEventDashboard from "@/src/components/SingleNimEvents/SingleEventDashboard";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Events | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <SingleEventDashboard />
    </div>
  );
};

export default page;
