import ReportDashboard from "@/src/components/Reports/ReportDashboard";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Reports | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <ReportDashboard />
    </div>
  );
};

export default page;
