import PaymentGatewaySelection from "@/src/components/PaymentGateway";
import SideNav from "@/src/components/SideNav";

import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Payment Gateway | NIM",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className="flex flex-col bg-[#F5F7FA] md:flex-row ">
      <SideNav />

      <div className="flex flex-col  w-full">
        <PaymentGatewaySelection />
      </div>
    </div>
  );
};
export default page;
