import PaymentGatewaySelection from "@/src/components/PaymentGateway";
import SideNav from "@/src/components/SideNav";
import { Metadata } from "next";
import { Suspense } from "react";
export const metadata: Metadata = {
title: "Payment Gateway | NIM",
  description: "Generated by create next app",
};
const Page = () => {
  return (
    <div className="flex flex-col bg-gray-50 md:flex-row">
      <Suspense fallback={<div>Loading navigation...</div>}>
        <SideNav />
      </Suspense>
      <Suspense fallback={<div>Loading payment gateway...</div>}>
        <main className="flex flex-col w-full">
          <PaymentGatewaySelection />
        </main>
      </Suspense>
    </div>
  );
};

export default Page;
