

import NimEvents from "@/src/components/NimEvents/NimEventsDashboard";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Admin Dashboard | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
    <NimEvents/>
    </div>
  );
};

export default page;
