import License from "@/src/components/License/License";

import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "License | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <License />
    </div>
  );
};

export default page;
