import ResetPassword from "@/src/components/ResetPassword";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Reset Password | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <ResetPassword />
    </div>
  );
};

export default page;
