import LoginForm from "@/src/components/Login";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Login | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <LoginForm/>
    </div>
  );
};

export default page;
