

import MemberDashboard from "@/src/components/Members/MemberDashboard";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Members | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <MemberDashboard/>
    </div>
  );
};

export default page;
