
import VerifyOTP from "@/src/components/VerifyOtp";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Verify OTP | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <VerifyOTP/>
    </div>
  );
};

export default page;
