import AdminDashboard from "@/src/components/Dashboard/AdminDashboard";

import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Dashboard | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <AdminDashboard />
    </div>
  );
};

export default page;
