
import NimVerification from "@/src/components/NimVerification/NimVerificationDashboard";

import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Admin Dashboard | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
    <NimVerification/>
    </div>
  );
};

export default page;
