

import NotificationDashboard from "@/src/components/Notification/NotifcationDashboard";
import { Metadata } from "next/types";
import React from "react";
export const metadata: Metadata = {
  title: "Notification | NIM",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
  <NotificationDashboard/>
    </div>
  );
};

export default page;
